name: naman Deployment EC2
 
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Manage Directory 
        run: |
          cd /home/ubuntu/naman-strategy-python-script

      - name: Pull latest code from stag
        run: |
          git pull https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/rahul-prajapati-cilans/naman-strategy-python-script.git develop
        working-directory: /home/ubuntu/naman-strategy-python-script
